# recipe.py
#
# Contains a recipe for a given model chemistry

import functools
import warnings
import copy

#######################################################
#
# Ingredient
#
class Ingredient:
    '''
    Placeholder class for an "Ingredient" in a model 
    chemistry. This will later be filled with information
    about calculations, basis-sets, and other relevant options

    Ingredient.name           : name of ingredient in dataset
    Ingredient.info           : information about ingredient
    Ingredient.from_transform : name of transformation that generated
                                this ingredient, otherwise 
                                
                                
    '''

    def __init__(self, name = None, info = None, from_transform = None):
        self.name = name
        self.info = info
        self.from_transform = from_transform

    def __str__(self):
        s = f"Ingredient {self.name}. "
        if self.info is not None:
            s += f"{self.info}"
        if (self.from_transform is None):
            s += "(Base Ingredient)"
        else:
            s += f"(formed from {self.from_transform})"
        return s

#None_Ingredient = Ingredient(name = "None Ingredient", info = "Empty Ingredient", from_transform = False)

#######################################################
# 
# Transformation
#
# 
#
class Transformation:
    '''
    Defines a transformation of ingredients and coefficients into a new ingredient.  

    Transformation.name     : name of transformation for hashing
    Transformation.func     : Function that applies transformation 
    Transformation.result   : Resulting ingredient
    Transformation.input    : Input ingredient dictionary
    Transformation.coefs    : Coefficient dictionary 

    The function the transformation executes must be formatted such that
    ingredient names are used to access dataframe columns, and coefs are 
    free to be anything.

    Maybe modify this to only work with ingredient lookup names? The whole, multiple ingredient
    thing is a little annoying
    
    def func(df, ingredient_dict, coef_dict):
        return df[ingredient_dict['some thing'].name] + coef_dict['other_thing']
    '''

    def __init__(self, name = None, func = None, result = None, ingredients = None, coefs = None):
        '''
        Initializes Transformation class
        '''
        self.name = name
        self.func = func
        self.result = result 
        self.ingredients = ingredients 
        self.coefs = coefs

    def __str__(self):
        '''
        Returns a string for printing class
        '''
        s = f"Transformation {self.name}\n"
        s += f"Result : {self.result.name}\n"
        s += f"Ingredients "
        for key,val in self.ingredients.items():
            s += f" {key} : {val.name}," 
        s += f"\nCoefficients"
        for key,val in self.coefs.items():
            s += f" {key} : {val}," 
        s += f"\nFunction : {self.func}\n"
        return s

    def apply(self, df):
        '''
        Apply the function to a dataframe
        '''
        return self.func(df, self.ingredients, self.coefs)


#######################################################
#
# Recipe class
#
# TODO: double check the whole "pass by reference" thing can't bite us...
#
# TODO: The transformations can lead to data dependencies, and we need to untangle
#       this via a recursive apply call
#       
# 
class Recipe:
    '''
    Class that contains a model chemistry "recipe", and the means to generate it
    from column transformations and "ingredients."

    Recipe.name             : name of the recipe
    Recipe.ingredients      : a dict of column ingredients that must be calculated
    Recipe.transformations  : a dictionary of new columns that are generated by 
                              transformations of old columns

    You can generate this class either dynamically (add ingredients and transformations), 
    or "intelligently" by defining a set of transformations that "back-fills" the ingredients 

    '''

    def __init__(self, name = None, ingredients = None,  transformations = None):
        '''
        Initialize the model chemistry. 

        ingredients : dictionary of ingredients 
        transformations : dictionary of 
        '''
        self.name = name

        self.ingredients = ingredients if ingredients is not None else {}
        self.transformations = {}

        if transformations is not None:
            for name, trans in transformations.items():
                self.add_transformation(trans)


    def __str__(self):
        '''
        Returns a printable string of the recipe
        '''
        s = f"Recipe {self.name}\n"
        s += "Ingredients:\n"
        for name, ingredient in self.ingredients.items():
            s += f"{ingredient.name}, " 
        s += "\nTransformations:\n"
        for name, transform in self.transformations.items():
            s += f"{transform.name}"
        return s

    #
    # Add a transformation to the dict
    #
    def add_transformation(self, transformation):
        '''
        Add a transformation to the Recipe.

        result_name     : name for the resulting column in the ingredient dictionary
        transformation  : Transformation class object 
        '''

        # Warn if we're overwriting  
        # Actually, this is somewhat the point of this, as this allows a minimal set of calculations 
        # to be constructed. Comment out
        #if name is in self.ingredients:
        #    warnings.warn(UserWarning(f"Ingredient {name} will be overwritten by transformation {transformation}"))            
        # Add the resulting ingredient
        self.ingredients[transformation.result.name] = transformation.result
        self.ingredients[transformation.result.name].from_transformation = True

        # Add the ingredients from the transform
        for name, ingredient in transformation.ingredients.items():
            self.ingredients[ingredient.name] = ingredient

        #add transformation
        self.transformations[transformation.name] = transformation

    # Add an ingredient to the dict
    def add_ingredient(self, ingredient):
        '''
        Adds ingredient to the list using name as a hash
        '''
        self.ingredients[ingredient.name] = ingredient

    # return list of the raw ingredients the user must externally calculate
    def raw_ingredients(self):
        '''
        Returns a list of the "raw" ingredients that cannot be derived via
        transformations and must be calculated.
        '''

        raw = {}

        for name, ingredient in self.ingredients.items():
            if not ingredient.from_transform:
                raw[name] = ingredient

        return raw

    # transformation order to avoid dependencies 
    def ordered_transforms(self):
        '''
        Returns the set of registered transformations
        in the order they must be performed to avoid dependencies
        
        NOTE: Placeholder, not currently implemented
        '''
        return None

        

