# recipe.py
#
# Contains a recipe for a given model chemistry

import functools
import warnings
import copy

#######################################################
#
# Ingredient
#
class Ingredient:
    '''
    Placeholder class for an "Ingredient" in a model 
    chemistry. This will later be filled with information
    about calculations, basis-sets, and other relevant options

    Ingredient.name           : name of ingredient for hashing
    Ingredient.info           : information about ingredient
    Ingredient.from_transform : boolean that indicates if this
                                ingredient was generated from a 
                                transformation or is "raw"
    '''

    def __init__(self, name = None, info = None, from_transform = False):
        self.name = name
        self.info = info
        self.from_transform = from_transform

    def __str__(self):
        s = f"Ingredient : {self.name}"
        if (not self.from_transform):
            s += "(Base Ingredient)"
        s += f"\n{self.info}"
        return s

#None_Ingredient = Ingredient(name = "None Ingredient", info = "Empty Ingredient", from_transform = False)

#######################################################
# 
# Transformation
#
# 
#
class Transformation:
    '''
    Defines a transformation of ingredients and coefficients into a new ingredient.  

    Transformation.name     : name of transformation for hashing
    Transformation.func     : Function that applies transformation 
    Transformation.result   : Resulting ingredient
    Transformation.input    : Input ingredient dictionary
    Transformation.coefs    : Coefficient dictionary 

    The function the transformation executes must be formatted such that
    ingredient names are used to access dataframe columns, and coefs are 
    free to be anything.
    
    def func(df, ingredient_dict, coef_dict):
        return df[ingredient_dict['some thing'].name] + coef_dict['other_thing']
    '''

    def __init__(self, name = None, func = None, result = None, ingredients = None, coefs = None):
        '''
        Initializes Transformation class
        '''
        self.name = name
        self.func = func
        self.result = result 
        self.ingredients = ingredients 
        self.coefs = coefs

    def __str__(self):
        '''
        Returns a string for printing class
        '''
        s = f"Transformation {self.name}\n"
        s += f"Result : {self.result.name}\n"
        s += f"Ingredients "
        for key,val in self.ingredients.items():
            s += f" {key} : {val.name}," 
        s += f"\nCoefficients"
        for key,val in self.coefs.items():
            s += f" {key} : {val}," 
        s += f"\nFunction : {self.func}\n"
        return s

    def apply(self, df):
        '''
        Apply the function to a dataframe
        '''
        return self.func(df, self.ingredients, self.coefs)


#######################################################
#
# Recipe class
#
class Recipe:
    '''
    Class that contains a model chemistry "recipe", and the means to generate it
    from column transformations and "ingredients."

    Recipe.name             : name of the recipe
    Recipe.ingredients      : a dict of column ingredients that must be calculated
    Recipe.transformations  : a dictionary of new columns that are generated by 
                              transformations of old columns

    You can generate this class either dynamically (add ingredients and transformations), 
    or "intelligently" by defining a set of transformations that "back-fills" the ingredients 

    '''

    def __init__(self, name = None, ingredients = None,  transformations = None):
        '''
        Initialize the model chemistry. 

        ingredients : dictionary of ingredients 
        transformations : dictionary of 
        '''
        self.name = name
        self.ingredients = ingredients if ingredients is not None else {}
        self.transformations = transformations if transformations is not None else {}


    def __str__(self):
        '''
        Returns a printable string of the recipe
        '''
        s = f"Recipe {self.name}"
        for name, ingredient in self.ingredients.items():
            s += f"{name} <- {ingredient}" 
        for name, transform in self.transformations.items():
            s += f"{name} <- {transformation}"
        return s

    # Add a transformation to the list
    #
    # TODO : 
    def add_transformation(self, result_name, transformation):
        '''
        Add a transformation to the Recipe.

        result_name     : name for the resulting column in the ingredient dictionary
        transformation  : Transformation class object 
        '''

        # Warn if we're overwriting  
        # Actually, this is somewhat the point of this, as this allows a minimal set of calculations 
        # to be constructed. Comment out
        #if name is in self.ingredients:
        #    warnings.warn(UserWarning(f"Ingredient {name} will be overwritten by transformation {transformation}"))            

        # Add the resulting ingredients
        self.ingredients[name] = Ingredient(info = name, from_transform = True)

        # Add the ingredients from the transform
        for name, ingredient in transformation.ingredients:
            self.ingredients[name] = ingredient

    def raw_ingredients(self):
        '''
        Returns a list of the "raw" ingredients that cannot be derived via
        transformations and must be calculated.
        '''

        raw = {}

        for name, ingredient in self.ingredients:
            if not ingredient.from_transform:
                raw[name] = ingredient

        return raw

        

